name: Merge master branch into gcp-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  merge-to-gcp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
        
      - name: Merging
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git checkout gcp-deploy
          git merge origin/master --no-edit
          git push origin gcp-deploy

        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
